
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Porta RabbitMQ (AMQP)
      - "15672:15672"  # Porta di management GUI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - usermanager-network

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8081:8080"  # Espone il servizio sulla porta 8081
    depends_on:
      - rabbitmq  # Assicura che RabbitMQ sia avviato prima del servizio
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - usermanager-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "8082:8080"  # Espone il servizio sulla porta 8082
    depends_on:
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - usermanager-network

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "8083:8080"  # Espone il servizio sulla porta 8083
    depends_on:
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - usermanager-network

networks:
  usermanager-network:
    driver: bridge
